services:
  redis:
    image: redis:7.2.4-alpine
    container_name: s5-redis
    volumes:
      - ${CONFIG_ROOT}/socks5-proxy/config/data:/data
  #    restart: always

  proxy:
    depends_on:
      - redis
    container_name: s5-proxy
    build: ${CONFIG_ROOT}/socks5-proxy/proxy
    volumes:
      - ${CONFIG_ROOT}/socks5-proxy/config/proxy:/app
      - /app/node_modules
    environment:
      APP_PORT: ${PROXY_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      REQUIRE_AUTH: 0
      REDIS_HOST: redis
      REDIS_PORT: ${SOCKS5_REDIS_PORT}
      REDIS_DB: 0
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
    expose:
      - "${PROXY_PORT}/tcp"
  #   restart: always

  telegram_bot:
    depends_on:
      - redis
    container_name: s5-telegram
    build: ${CONFIG_ROOT}/socks5-proxy/config/telegram-bot
    volumes:
      - ${CONFIG_ROOT}/socks5-proxy/config/telegram-bot:/app
      - /app/node_modules
    environment:
      APP_PORT: ${PROXY_PORT}
      BOT_APP_PORT: ${TELEGRAM_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      REDIS_HOST: redis
      REDIS_PORT: ${SOCKS5_REDIS_PORT}
      REDIS_DB: 0
      PUBLIC_URL: t.me/socks5proxyserver_bot
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
      TELEGRAM_USE_WEBHOOKS: 0
      TELEGRAM_WEBHOOK_URL: /webhook
      NTBA_FIX_319: 1
    ports:
      - "${TELEGRAM_PORT}:${TELEGRAM_PORT}"
    expose:
      - "${TELEGRAM_PORT}/tcp"
      #  restart: always
      
networks:
  default:
    external: true
    name: ${INFRA_NET}
