services:
  pihole:
    container_name: pihole
    hostname: home.pihole
    image: pihole/pihole:latest
    environment:
      TZ: ${TZ}
      WEB_PORT: 80
      FTLCONF_LOCAL_DOMAIN: "lan"
      FTLCONF_LOCAL_IPV4: "${LAN_IPV4}"
      FTLCONF_dns_listeningMode: "all"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${PIHOLE_WEBUI_PORT}:80/tcp"
    volumes:
      - ./etc-pihole:/etc/pihole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    depends_on:
      - unbound
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`${PIHOLE_HOST}`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=cf"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.docker.network=${TRAEFIK_NET}"
    healthcheck:
      test: ["CMD", "pihole", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - default
      - traefik_net
    restart: unless-stopped
    
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    restart: unless-stopped
#     ports:
#       - "${UNBOUND_PORT}:53/tcp"
#       - "${UNBOUND_PORT}:53/udp"
    healthcheck:
      test: ["CMD", "drill", "@127.0.0.1", "google.com"]
      interval: 60s
      timeout: 10s
      retries: 3

networks:
  default:
    external: true
    name: ${DNS_NET}
  traefik_net:
    external: true
    name: ${TRAEFIK_NET}
