services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./config:/usr/share/nginx/html:ro
    ports:
      - "${NGINX_PORT}:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`${NGINX_HOST}`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=cf"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.docker.network=${TRAEFIK_NET}"

networks:
  default:
    external: true
    name: ${TRAEFIK_NET}
