services:
  portainer:
    image: portainer/portainer-ee:alpine
    container_name: portainer
    ports:
      - ${PORTAINER_PORT}:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_HOST}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=cf"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=${TRAEFIK_NET}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9000/api/status"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - default
      - traefik_net
  portainer-agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    ports:
      - "${PORTAINER_AGENT_PORT}:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped

volumes:
  data:
networks:
  default:
    external: true
    name: ${INFRA_NET}
  traefik_net:
    external: true
    name: ${TRAEFIK_NET}
