---
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "${FLARESOLVERR_PORT:-8191}:8191"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flaresolverr.rule=Host(`${FLARESOLVERR_HOST}`)"
      - "traefik.http.routers.flaresolverr.entrypoints=websecure"
      - "traefik.http.routers.flaresolverr.tls=true"
      - "traefik.http.routers.flaresolverr.tls.certresolver=cf"
      - "traefik.http.services.flaresolverr.loadbalancer.server.port=8191"
      - "traefik.docker.network=${TRAEFIK_NET}"
    restart: unless-stopped
    networks:
      - default
      - traefik_net
networks:
  default:
    external: true
    name: ${MEDIA_NET}
  traefik_net:
    external: true
    name: ${TRAEFIK_NET}
